version: '3'
services:
  jdk21:
    image: opensearchproject/opensearch:2.12.0
    ports:
      - 9201:9200
    environment:
      - cluster.name=jdk21
      - node.name=jdk21
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=La6ohgaighei
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
  jdk17:
    build: .
    ports: 
      - 9202:9200
    environment:
      - cluster.name=jdk17
      - node.name=jdk17
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=La6ohgaighei
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"